# Site settings
title: Innku
email: info@innku.com
description: We are experts in creating software products. We develop web solutions, accessible and ready to use in weeks.
baseurl: "/innku-2016" # the subpath of your site, e.g. /blog
url: "hhttp://innku.github.io/innku-2016" # the base hostname & protocol for your site
twitter_username: innku
github_username: innku


# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
