# Site settings
title: Innku
email: info@innku.com
description: We are experts in creating software products. We develop web solutions, accessible and ready to use in weeks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.innku.com" # the base hostname & protocol for your site
twitter_username: innku
github_username: innku

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
